sonar.projectKey=Job-Portal-Microservices
sonar.projectName=Job Portal Microservices
sonar.host.url=http://localhost:9000

sonar.sources=.
sonar.tests=.
sonar.inclusions=**/src/main/**,frontend/src/**
sonar.test.inclusions=**/src/test/**,frontend/src/**/*.spec.ts
sonar.exclusions=**/target/**,**/node_modules/**,**/dist/**,**/build/**,**/*.log

sonar.java.binaries=**/target/classes
sonar.coverage.jacoco.xmlReportPaths=**/target/site/jacoco/jacoco.xml
sonar.coverage.exclusions=**/*Application.java,**/config/**,**/dto/**,**/model/**,**/events/**,**/outbox/**,**/exception/**,**/repository/**,**/client/**
