server.port=8080
spring.application.name=api-gateway

spring.config.import=optional:configserver:http://localhost:8888

spring.cloud.gateway.discovery.locator.enabled=false

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

jwt.secret=${JWT_SECRET:j0bP0rt@lS3cur3S3cr3tK3y!XyZ#2024$AbCdEfGhIjKlMnOpQrStUvWxYz12}

management.endpoints.web.exposure.include=health,info,gateway
