server.port=8081
spring.application.name=user-service

spring.config.import=optional:configserver:http://localhost:8888

# PostgreSQL - jobportal_users
spring.datasource.url=jdbc:postgresql://localhost:5432/jobportal_users
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# JWT
jwt.secret=${JWT_SECRET:j0bP0rt@lS3cur3S3cr3tK3y!XyZ#2024$AbCdEfGhIjKlMnOpQrStUvWxYz12}
jwt.expiration=86400000

spring.security.user.name=disabled
spring.security.user.password=disabled
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

management.endpoints.web.exposure.include=health,info
